# Generated by Django 6.0.4 on 2026-05-07 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0013_alter_productvariant_discount_percentage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        default=orders.models.generate_order_number,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("shipped", "Shipped"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cod", "Cash on Delivery")],
                        default="cod",
                        max_length=20,
                    ),
                ),
                ("shipping_full_name", models.CharField(max_length=100)),
                ("shipping_phone", models.CharField(max_length=15)),
                ("shipping_address_line_1", models.CharField(max_length=255)),
                (
                    "shipping_address_line_2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("shipping_city", models.CharField(max_length=100)),
                ("shipping_state", models.CharField(max_length=100)),
                ("shipping_postal_code", models.CharField(max_length=20)),
                ("shipping_country", models.CharField(default="India", max_length=100)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "shipping_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=150)),
                (
                    "variant_sku",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "device_model",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("case_type", models.CharField(blank=True, default="", max_length=50)),
                ("color", models.CharField(blank=True, default="", max_length=50)),
                ("color_code", models.CharField(blank=True, default="", max_length=7)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "custom_text",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "custom_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="order_customizations/"
                    ),
                ),
                (
                    "item_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("returned", "Returned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                ("return_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, default="", max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
