# Generated by Django 6.0.4 on 2026-06-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_customization_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid via COD or Razorpay', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid from wallet', max_digits=10),
        ),
    ]
