# Generated by Django 6.0.4 on 2026-04-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productspecification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allow_custom_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='allow_custom_text',
        ),
    ]
