# Generated by Django 6.0.4 on 2026-05-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_category_has_device_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_trending",
            field=models.BooleanField(default=False),
        ),
    ]
