# Generated by Django 6.0.4 on 2026-05-04 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_is_featured_product_is_trending"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="discount_percentage",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(90)]
            ),
        ),
    ]
