# Generated by Django 6.0.4 on 2026-05-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productvariant_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='device_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('laptop', 'Laptop')], default='phone', max_length=10),
        ),
    ]
