# Generated by Django 6.0.4 on 2026-06-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productvariant_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='discount_percentage',
        ),
    ]
