# Generated by Django 6.0.4 on 2026-08-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_category_requires_device_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="case_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("slim", "Slim Fit"),
                    ("rugged", "Rugged Armor"),
                    ("wallet", "Wallet Folio"),
                    ("clear", "Crystal Clear"),
                    ("leather", "Leather Finish"),
                    ("magsafe", "MagSafe Compatible"),
                    ("bumper", "Bumper Case"),
                    ("military", "Military Grade"),
                    ("thin", "Ultra Thin"),
                    ("matte", "Matte Finish"),
                    ("other", "Other"),
                    ("full_cover", "Full Cover"),
                    ("top_cover", "Top Cover Only"),
                    ("bottom_cover", "Bottom Cover Only"),
                    ("palm_rest", "Palm Rest Cover"),
                    ("full_body_wrap", "Full Body Wrap"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
