# Generated by Django 6.0.4 on 2026-05-04 06:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_cartitem_custom_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="custom_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="custom_image"
            ),
        ),
    ]
