# Generated by Django 6.0.4 on 2026-07-07 17:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='referral_enabled',
            field=models.BooleanField(default=True, help_text='Master on/off switch for the referral program. When off, new signups do not earn referral credit and no new referrals are recorded. Existing referrals are still honoured.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='referred_reward_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Wallet credit given to the NEW USER immediately when they sign up using a valid referral code.', max_digits=8),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='referrer_reward_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Wallet credit given to the REFERRER after the person they invited places their first order. Amount is locked onto each referral when it is created.', max_digits=8),
        ),
    ]
